version: '3.9'

volumes:
    db_data:
    rage:

services:
    rage:
        build:
            context: .
            dockerfile: .docker/rage/Dockerfile
        volumes:
            - /opt/ragemp_server:/server
        ports:
            - '22005:22005/udp'
            - 22006:22006
        restart: unless-stopped
        tty: true
        stdin_open: true

    vue:
        build:
            context: ./phenixgames-v3-vue
            dockerfile: .docker/Dockerfile
        volumes:
            - .:/vue
        working_dir: /vue
        ports:
            - 3000:3000
        depends_on:
            - rage
        stdin_open: true

    mysql:
        build:
            context: ../../.
            dockerfile: .docker/mysql/Dockerfile
        container_name: mysql
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 3306:3306
        restart: unless-stopped
        depends_on:
            - rage
        stdin_open: true
