#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

PRETTIER_CHANGES=$(echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --list-different)

if [ -n "$PRETTIER_CHANGES" ]; then
  echo "Prettier found Prettier changes in the following files:"
  echo "$PRETTIER_CHANGES" | sed 's|\\ | |g'
  echo "Please run prettier on your changes before committing." >&2
  exit 1
fi

exit 0