name: Add bugs and prs to default Milestone

on:
    issues:
        types:
            - opened
    pull_request:
        types:
            - opened

jobs:
    add-to-project:
        name: Add to Milestone
        runs-on: ubuntu-latest
        steps:
            - uses: andrefcdias/add-to-milestone
              with:
                  repo-token: '${{ secrets.ADD_PROJECT_MILESTONE }}'
                  milestone: 'Beta 0.1'